const tpain = document.querySelector('#tpain')
const donny = document.querySelector('#donny')
const gladys = document.querySelector('#gladys')
const joey = document.querySelector('#joey')
const rumer = document.querySelector('#rumer')
const latoya = document.querySelector('#latoya')
const ricki = document.querySelector('#ricki')
const tori = document.querySelector('#tori')
const margaret = document.querySelector('#margaret')
const terry = document.querySelector('#terry')
const tommy = document.querySelector('#tommy')
const antonio = document.querySelector('#antonio')

document.querySelector('#tpainWho').addEventListener('click', tpainWho)
document.querySelector('#donnyWho').addEventListener('click', donnyWho)
document.querySelector('#gladysWho').addEventListener('click', gladysWho)
document.querySelector('#joeyWho').addEventListener('click', joeyWho)
document.querySelector('#rumerWho').addEventListener('click', rumerWho)
document.querySelector('#latoyaWho').addEventListener('click', latoyaWho)
document.querySelector('#rickiWho').addEventListener('click', rickiWho)
document.querySelector('#toriWho').addEventListener('click', toriWho)
document.querySelector('#margaretWho').addEventListener('click', margaretWho)
document.querySelector('#terryWho').addEventListener('mouseover', terryWho)
document.querySelector('#tommyWho').addEventListener('mouseover', tommyWho)
document.querySelector('#antonioWho').addEventListener('mouseover', antonioWho)



function tpainWho (){
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
	joey.classList.add('hidden')
    rumer.classList.add('hidden')
	latoya.classList.add('hidden')
	ricki.classList.add('hidden')
    tori.classList.add('hidden')
	margaret.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	tpain.classList.toggle('hidden')
}

function donnyWho(){
	tpain.classList.add('hidden')
	gladys.classList.add('hidden')
	joey.classList.add('hidden')
    rumer.classList.add('hidden')
	latoya.classList.add('hidden')
	ricki.classList.add('hidden')
    tori.classList.add('hidden')
	margaret.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	donny.classList.toggle('hidden')
}

function gladysWho (){
	tpain.classList.add('hidden')
	donny.classList.add('hidden')
	joey.classList.add('hidden')
    rumer.classList.add('hidden')
	latoya.classList.add('hidden')
	ricki.classList.add('hidden')
    tori.classList.add('hidden')
	margaret.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	gladys.classList.toggle('hidden')
}

function joeyWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    rumer.classList.add('hidden')
	latoya.classList.add('hidden')
	ricki.classList.add('hidden')
    tori.classList.add('hidden')
	margaret.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	joey.classList.toggle('hidden')
}
function rumerWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    joey.classList.add('hidden')
	latoya.classList.add('hidden')
	ricki.classList.add('hidden')
    tori.classList.add('hidden')
	margaret.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	rumer.classList.toggle('hidden')
}
function latoyaWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    joey.classList.add('hidden')
	rumer.classList.add('hidden')
	ricki.classList.add('hidden')
    tori.classList.add('hidden')
	margaret.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	latoya.classList.toggle('hidden')
}
function rickiWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    joey.classList.add('hidden')
	rumer.classList.add('hidden')
	latoya.classList.add('hidden')
    tori.classList.add('hidden')
	margaret.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	ricki.classList.toggle('hidden')
}
function toriWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    joey.classList.add('hidden')
	rumer.classList.add('hidden')
	latoya.classList.add('hidden')
    ricki.classList.add('hidden')
	margaret.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	tori.classList.toggle('hidden')
}
function margaretWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    joey.classList.add('hidden')
	rumer.classList.add('hidden')
	latoya.classList.add('hidden')
    ricki.classList.add('hidden')
	tori.classList.add('hidden')
	terry.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	margaret.classList.toggle('hidden')
}
function terryWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    joey.classList.add('hidden')
	rumer.classList.add('hidden')
	latoya.classList.add('hidden')
    ricki.classList.add('hidden')
	tori.classList.add('hidden')
	margaret.classList.add('hidden')
    tommy.classList.add('hidden')
	antonio.classList.add('hidden')
	terry.classList.toggle('hidden')
}
function tommyWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    joey.classList.add('hidden')
	rumer.classList.add('hidden')
	latoya.classList.add('hidden')
    ricki.classList.add('hidden')
	tori.classList.add('hidden')
	margaret.classList.add('hidden')
    terry.classList.add('hidden')
	antonio.classList.add('hidden')
	tommy.classList.toggle('hidden')
}
function antonioWho(){
    tpain.classList.add('hidden')
	donny.classList.add('hidden')
	gladys.classList.add('hidden')
    joey.classList.add('hidden')
	rumer.classList.add('hidden')
	latoya.classList.add('hidden')
    ricki.classList.add('hidden')
	tori.classList.add('hidden')
	margaret.classList.add('hidden')
    terry.classList.add('hidden')
	tommy.classList.add('hidden')
	antonio.classList.toggle('hidden')
}